### ISSUE TITLE
Error ffmpeg gcc cannot create executable file

### ISSUE THREAD

**Issue by munfesansev** [jb-alvarado/compile-ffmpeg-osx-linux#1]
Im compiling this code in a clean Ubuntu 16.04 .

Im getting the "gcc cannot create executable file" when compiling ffmpeg.

I disabled all optional libraries. 

What can I do?

**Comment by jb-alvarado** [comment]
Have you install all the necessary tools and libs? You could also look in the file: ffbuild/config.log. At the end it says more clear, what is happen.
