### ISSUE TITLE
Build static dependency problem.

### ISSUE THREAD

**Issue by nickverlinden** [jb-alvarado/compile-ffmpeg-osx-linux#2]
Hi,

I'm trying to build a portable version of the ffmpeg binary with decklink support so that I can distribute it on different systems (for personal use of coarse). When I build ffmpeg on macos 10.14, and try to run the compiled binary on macos 10.13, i get a dependency error stating that liblzma is an incompatible version, 8.0.0 is required, while 5.0.0 is provided.

I have set ffmpeg_shared="", so it should build a version that has all static libs included right?
Related, I would like to include sdl2 support, but when compiling the same problem comes up. When running the compiled binary on other systems it states that the sdl2 dylib is missing from the system. I could live without sdl support, so this is not a big issue, but it's probably related.

Kind regards,
Nick

**Comment by jb-alvarado** [comment]
Hi,
at the moment I can not test this on a mac. But ffmpeg try to catch libs from the system, when it finds them there. I think this is the problem with libzma. You could extent the build script to add this libs and build them statically or you disable them in ffmpeg with **--disable-lmza** 

I remember that sdl2 was a bit complicate to integrate in ffmpeg, specially under linux. The easiest would be that you install the sdl2 lib with **brew** on your target machine.

**Comment by nickverlinden** [comment]
Hi,

Thank you for the info. Added the --disable-lmza parameter, but ffmpeg won't build.

This is taking a bit too much of my time due to inexperience. I'm looking for a freelancer who could provide me a static portable binary of ffmpeg 4.1 for all three major platforms: linux (64 bit), windows (64 bit) and macos. If you are interested or know anyone, please contact me.

Thank you,
Nick

**Comment by jb-alvarado** [comment]
And the static build from the official web page are not ok for you?

When you have a bit patience - on Monday I could look to this problem...

**Comment by nickverlinden** [comment]
Hi,

No, unfortunatly they don't have decklink support. This is absolutely required for the project I'm working on. Sure, I can wait a little bit. That is very kind of you.

Kind regards,
Nick

**Comment by jb-alvarado** [comment]
Ok you can try the new version. This should work in Linux and macOS. There is a way tho make it even more static then now, but then I can not guarantee that ffmpeg with decklink will run normal.

For now I would recommend to disable ffplay / SDL2, they have more system dependencies.

**Comment by nickverlinden** [comment]
Great, after some modifications it worked like a charm. I made a fork and submitted a pull request with some changes. I got Network errors with some videolan.org git repos. When I checked the site, it said they are moving git repos, so I went ahead and changed some urls.
Als building for linux, I'll let you know how that works out :-).

**Comment by jb-alvarado** [comment]
Nice - good to hear that it worked :)
